### ISSUE TITLE
trouble installing clrsvsim

### ISSUE THREAD

**Issue by fkcoolman** [color/clrsvsim#7]
Hi there,

I am trying to use clrsvsim to simulate some dataset to test our pipeline, after I made a python sandbox with all the prerequisites satisfied, I use python setup.py instal to install clrsvsim, no error or warnings occurred, following is the last few lines appeared on my terminal:

Using /share/home/kai.feng/env/ve-clrsvsim/lib/python2.7/site-packages
Finished processing dependencies for clrsvsim==0.0.1

after this, I try to use the command in README to test clrsvsim, and I cannot execute the command, is there a detailed readme about how to use clrsvsim or there are something wrong during my installation?

Thanks,

Kai

**Comment by giladmishne** [comment]
Hi Kai,

Can you paste the error message you're getting?

Thanks!

**Comment by fkcoolman** [comment]
Hi giladmishne,

The problem is I don't know how to use clrsvsim, after I install clrsvsim, there is no bash command:

$modfiy_copy_number
-bash: modfiy_copy_number: command not found

your readme has no instructions on how to use it, is clrsvsim a python module that I should write a script to use it ?

Thanks, 

Kai

**Comment by giladmishne** [comment]
Sorry, yes it is a library. I will add a better usage example in a day or two.

**Comment by fkcoolman** [comment]
appreciate your help, I write a python script and clrsvsim worked, it is a wonderful tool, wish you can  make a better instruction that everyone could use it.

Kai
